### PR TITLE
Units for theoretical_pitch are in Hz

### PR DESCRIPTION
**Pull request by pelinski**
Hi! @marinaniet0 and I realized this while working in the Audio and Muisc Processing Lab assignment:

In line 73: 

```
                        theoretical_pitch = Converter.cent_to_hz(
                            note_cent, tonic_hz)
```
So `theoretical_pitch` must be in Hz when written to the `stable_notes`dict.

### CODE REVIEW

**Comment by sertansenturk** [comment]
Thank you @pelinski and @marinaniet0 not only for reporting the issue but also for making the fix! 🥳 

Before I approve the PR can you also do the following:

- Increment the version to v0.14.2 in package [__init__.py](https://github.com/marter0/tomato/blob/master/src/tomato/__init__.py)
- Add the new version and a brief explanation to the [changelog](https://github.com/marter0/tomato/blob/master/Changelog.md)
- Last and most important. Can you add yourselves to the [Contributors](https://github.com/marter0/tomato/blob/master/CONTRIBUTORS)? 

Thanks in advance!

**Comment by pelinski** [comment]
Done! Thank you for considering the PR and for the toolbox :-)

**Comment by sertansenturk** [comment]
My pleasure. I'm glad that whatever I did years ago is of some help to you people :)

FYI, Before hitting the merge I've realized that the automated tests are failing. It's not because of your change, but something irrelevant. I've changed the PR to merge to the dev branch so I can fix these problems before pushing to master and creating a problematic release :smile: 

Thanks for the contributions!

**Review by sertansenturk — APPROVED** [review]
linting borken on Python. It's my problem. 

Merging to dev so I can fix these on my own before merging to master.

Thanks!

**Pull request merged**
